Comment code coverage before potentially failing.
Only fail on total coverage, not single file.

diff --git a/.github/workflows/code_coverage.yml b/.github/workflows/code_coverage.yml
--- a/.github/workflows/code_coverage.yml
+++ b/.github/workflows/code_coverage.yml
@@ -36,19 +36,20 @@ jobs:
         cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
         cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
 
-    - name: Coverage single fail - exit
-      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
-      run: |
-        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
-        exit 1
-
-    - name: Coverage total fail - exit
-      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
-      run: |
-        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
-        exit 1
-
     - name: Commit pytest coverage table
       uses: peter-evans/commit-comment@v1
       with:
         body: ${{ steps.pytester-cov.outputs.output-table }}
+
+#    - name: Coverage single fail - exit
+#      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+#      run: |
+#        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+#        exit 1
+
+    - name: Coverage total fail - exit
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+      run: |
+        echo "cov total fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+        echo "coverage report ${{ steps.pytester-cov.outputs.output-table }}"
+        exit 1
