Update code coverage with a lower limit on allowed coverage.
Update when workflow is triggered

diff --git a/.github/workflows/code_coverage.yml b/.github/workflows/code_coverage.yml
--- a/.github/workflows/code_coverage.yml
+++ b/.github/workflows/code_coverage.yml
@@ -1,14 +1,19 @@
 name: pytester-cov workflow
 
-on: [push, pull_request]
+on:
+  workflow_dispatch:
+  pull_request:
+    types: [opened, synchronize, reopened]
+    branches:
+    - main
 
 jobs:
-  build:
+  coverage:
 
     runs-on: ubuntu-latest
     env:
-      COVERAGE_SINGLE: 60
-      COVERAGE_TOTAL: 60
+      COVERAGE_SINGLE: 50
+      COVERAGE_TOTAL: 50
 
     steps:
     - uses: actions/checkout@v2
@@ -27,21 +32,21 @@ jobs:
       uses: alexanderdamiani/pytester-cov@v1.2.0
       with:
         pytest-root-dir: '.'
-        cov-omit-list: 'tests/*, docs/*, setup.py'
+        cov-omit-list: 'tests/*, docs/*, setup.py, examples/*'
         cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
         cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
 
-#    - name: Coverage single fail - exit
-#      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
-#      run: |
-#        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
-#        exit 1
-#
-#    - name: Coverage total fail - exit
-#      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
-#      run: |
-#        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
-#        exit 1
+    - name: Coverage single fail - exit
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+      run: |
+        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+        exit 1
+
+    - name: Coverage total fail - exit
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+      run: |
+        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+        exit 1
 
     - name: Commit pytest coverage table
       uses: peter-evans/commit-comment@v1
